### ISSUE TITLE
How do you export the .mlmodel file

### ISSUE THREAD

**Issue by mazzzystar** [ynagatomo/ImgGenSD2#2]
As I followed Apple's [step](https://github.com/apple/ml-stable-diffusion), the model I converted was `.mlpackage`, I could not load in CoreML using your repo.

However, I could load succeessfully using `.mlmodelc` file, so I wonder how could I export that file using Apple's guide.

Many thanks!

**Comment by ynagatomo** [comment]
Hi. I explained about that in README.md. Please use the `--bundle-resources-for-swift-cli` option when you convert the PyTorch model. With that option, it generates `.mlmodelc` files. :)

<img width="904" alt="Screenshot 2022-12-08 at 23 22 19" src="https://user-images.githubusercontent.com/66309582/206470705-5a71ed8d-bd53-41cf-b566-2a2d595e9b88.png">
