### ISSUE TITLE
iPhoneXR iOS16.2 crashed

### ISSUE THREAD

**Issue by Tongzhou-Yu** [ynagatomo/ImgGenSD2#4]

**Comment by ynagatomo** [comment]
Unfortunately, iPhone XR/A12 is not compatible with apple/ml-stable-diffusion. iPhone 12/A14+ is compatible, but running on iPhone seems to have problems now.
Even iPhone 14 is not working properly.: https://github.com/apple/ml-stable-diffusion/issues

**Comment by Tongzhou-Yu** [comment]
> 

What confuse me is that there is an application called Draw Things can be downloaded from App Store, which can run SD1.4\1.5 and other models in iPhone XR

**Comment by Tongzhou-Yu** [comment]
I found Draw Things has done an awesome work https://liuliu.me/eyes/stretch-iphone-to-its-limit-a-2gib-model-that-can-draw-everything-in-your-pocket/
