### ISSUE TITLE
Converter stuck at converting uNet

### ISSUE THREAD

**Issue by blu-Fox** [ynagatomo/ImgGenSD2#5]
The conversion process has been stuck at converting uNet for hours now.

<img width="565" alt="Screenshot 2022-12-17 at 10 01 03" src="https://user-images.githubusercontent.com/96650987/208234388-cb1af7cb-064c-4d81-a8b7-696c2310ddcd.png">

In activity monitor, I can see ANECompilerService using CPU, and Python 3.8 and ANECompilerService using RAM. However, Terminal does not use any Energy, leading me to assume the process got frozen or killed.

What can I do to resolve this? Wouldn't it be easier to be able to download an already converted coreML model?

MacBook Pro, M1 Pro, 16GB RAM

**Comment by ynagatomo** [comment]
I converted the Stable Diffusion v2 models to CoreML models today again (Dec 17, 2022), to compare with your result. I completed the conversion. Please check my console output on Gist: https://gist.github.com/ynagatomo/b483bfe15b520724c55eaa6ec6ceef62.

The Huggingface's converted models of v1.5 and v2 don't work well. They fail to create a stable-diffusion pipeline.

If you need converted models of SD v2 for just testing, send an email to me. The address is on the page: https://www.atarayosd.com/developer.html. :)

**Comment by blu-Fox** [comment]
Thank you. I'm pretty sure the system is just taking a very long time converting the model, and the process may not succeed every time due to limited RAM. 
For now, I downloaded pre-converted models from https://huggingface.co/apple
I managed to make v1.5 work in Python using Terminal. Tomorrow I will try V2, and then Swift next week
