### ISSUE TITLE
Real phone debugging work fine, but when running with a real phone alone app crashed

### ISSUE THREAD

**Issue by jiangdi0924** [ynagatomo/ImgGenSD2#8]
* iPhone 14
* iOS 16.2

Real phone debugging work fine, but when running with a real phone alone app crashed
![395761672886547_ pic](https://user-images.githubusercontent.com/21988177/210693622-d532cfa2-f7d9-4d57-b69a-dc126976baf4.jpg)

**Comment by ynagatomo** [comment]
Thank you for trying this app with a real phone. 
Unfortunately, I don't have the same iPhone to test your situation but this capability setting may help you when it is a memory limitation issue.
<img width="983" alt="Screenshot 2023-01-05 at 12 23 04" src="https://user-images.githubusercontent.com/66309582/210695209-e8b9fdc7-45e8-4f50-af6f-44bbed933243.png">

**Comment by jiangdi0924** [comment]
Thanks for the reply, I turned on `Increase Memory Limit` and `Extended Virtual Address Space` running with a real phone alone also crash. Very strange, real machine debugging is possible

> Thank you for trying this app with a real phone. Unfortunately, I don't have the same iPhone to test your situation but this capability setting may help you when it is a memory limitation issue. <img alt="Screenshot 2023-01-05 at 12 23 04" width="983" src="https://user-images.githubusercontent.com/66309582/210695209-e8b9fdc7-45e8-4f50-af6f-44bbed933243.png">

Thanks for the reply, I turned on `Increase Memory Limit` and `Extended Virtual Address Space` running with a real phone alone also crash. Very strange, real machine debugging is possible

**Comment by ynagatomo** [comment]
Hmm, very strange. If I get a chance, I will try the same.

**Comment by ynagatomo** [comment]
I wonder if the same thing will happen with this project.
- https://github.com/ynagatomo/ARDiffMuseum

**Comment by jiangdi0924** [comment]
I will do further testing on devices with more memory space, ml-stable-diffusion is marked with a minimum device version requirement of **iPhone 12 pro**

**Comment by ynagatomo** [comment]
Yes, That's right. I'm not sure if the requirement means the Pro series only.
It might make sense to experiment with other SD versions if possible. SD v1.4/v1.5/v2.0/v2.1.

**Comment by ynagatomo** [comment]
With my iPad Pro 2020/A12Z, it works alone. It is not a compatible device though.
The iPad Pro/M1 and M2 are supported. The iPad Air/M1 is not supported.
`Pro` is required?

**Comment by jiangdi0924** [comment]
I finally find it's work on my iPone14🫣

**Comment by ijunfly** [comment]
@jiangdi0924  Hello, how did you succeed? I have always failed
